-- Diccionario de frases sueltas -> SKU base, para el parser de "Pegar texto"
-- de carga masiva (ventas/compras/cambios). Importado desde la hoja
-- "Diccionario" de Master ownstyle real.xlsx.
CREATE TABLE IF NOT EXISTS diccionario_productos (
  id_diccionario SERIAL PRIMARY KEY,
  frase VARCHAR(200) NOT NULL,
  sku_base VARCHAR(100) NOT NULL,
  marca VARCHAR(100),
  modelo VARCHAR(100),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_diccionario_frase ON diccionario_productos(frase);

INSERT INTO diccionario_productos (frase, sku_base, marca, modelo) VALUES
  ('Airforce', 'AIRFORCE-BLANCA-XX', 'Airforce', 'Airforce Blanca'),
  ('AIRFROCE', 'AIRFORCE-BLANCA-XX', 'Airforce', 'Airforce Blanca'),
  ('Air force', 'AIRFORCE-BLANCA-XX', 'Airforce', 'Airforce Blanca'),
  ('Nike Airforce', 'AIRFORCE-BLANCA-XX', 'Airforce', 'Airforce Blanca'),
  ('Jordan baja', 'JORDAN-PANDA-XX', 'Jordan', 'Panda'),
  ('Jordan panda', 'JORDAN-PANDA-XX', 'Jordan', 'Panda'),
  ('Jordan bota', 'JORDAN-BOTA-XX', 'Jordan', 'Bota'),
  ('Bota', 'JORDAN-BOTA-XX', 'Jordan', 'Bota'),
  ('Nike 270 clásica', 'NIKE-270-CLAS-XX', 'Nike', '270'),
  ('270 clásica', 'NIKE-270-CLAS-XX', 'Nike', '270'),
  ('270 clasics', 'NIKE-270-CLAS-XX', 'Nike', '270'),
  ('270 clasixs', 'NIKE-270-CLAS-XX', 'Nike', '270'),
  ('Nike 270 black', 'NIKE-270-BLK-XX', 'Nike', '270'),
  ('270 black', 'NIKE-270-BLK-XX', 'Nike', '270'),
  ('React blanca', 'NIKE-REACTBLANCA-XX', 'Nike', 'React Blanca'),
  ('Nike React blanca', 'NIKE-REACTBLANCA-XX', 'Nike', 'React Blanca'),
  ('React clásica', 'NIKE-REACTCLASICA-XX', 'Nike', 'React Clasica'),
  ('Nike React clásica', 'NIKE-REACTCLASICA-XX', 'Nike', 'React Clasica'),
  ('Campus clásica', 'CAMPUS-CLASICA-XX', 'Campus', 'Campus Clasica'),
  ('Campus clasica', 'CAMPUS-CLASICA-XX', 'Campus', 'Campus Clasica'),
  ('Campus clasixs', 'CAMPUS-CLASICA-XX', 'Campus', 'Campus Clasica'),
  ('Campus clasics', 'CAMPUS-CLASICA-XX', 'Campus', 'Campus Clasica'),
  ('Campus gris', 'CAMPUS-GRIS-XX', 'Campus', 'Campus Gris'),
  ('Campus full blanca', 'CAMPUS-FULLBLANCA-XX', 'Campus', 'Campus Full Blanca'),
  ('Campus blanca', 'CAMPUS-FULLBLANCA-XX', 'Campus', 'Campus Full Blanca'),
  ('Campus full negra', 'CAMPUS-BLACK-XX', 'Campus', 'Campus Black'),
  ('Campus negra', 'CAMPUS-BLACK-XX', 'Campus', 'Campus Black'),
  ('Campus roja', 'CAMPUS-ROJO-XX', 'Campus', 'Campus Rojo'),
  ('Campus verde', 'CAMPUS-VERDE-XX', 'Campus', 'Campus Verde'),
  ('Campus BN', 'CAMPUS-NUEVABN-XX', 'Campus', 'Campus BN'),
  ('Campus NB', 'CAMPUS-NUEVANEGRA-XX', 'Campus', 'Campus NB'),
  ('Puma clásica', 'PUMA-CLASICA-XX', 'Puma', 'Puma Clasica'),
  ('Puma clasica', 'PUMA-CLASICA-XX', 'Puma', 'Puma Clasica'),
  ('Puma blanca', 'PUMA-BLANCA-XX', 'Puma', 'Puma Blanca'),
  ('Puma gris', 'PUMA-GRIS-XX', 'Puma', 'Puma Gris'),
  ('Knu clásica', 'VANS-CLASICA-XX', 'Vans', 'Vans Clasica'),
  ('Knu clasica', 'VANS-CLASICA-XX', 'Vans', 'Vans Clasica'),
  ('Knu clasics', 'VANS-CLASICA-XX', 'Vans', 'Vans Clasica'),
  ('Knu clasixs', 'VANS-CLASICA-XX', 'Vans', 'Vans Clasica'),
  ('Knu gris', 'VANS-GRIS-XX', 'Vans', 'Vans Gris'),
  ('Knu blanca', 'VANS-BLANCA-XX', 'Vans', 'Blanca'),
  ('Knu base marrón', 'VANS-MARRON-XX', 'Vans', 'Marron'),
  ('Knu base marron', 'VANS-MARRON-XX', 'Vans', 'Marron'),
  ('Hyline blanca', 'VANS-HIGHTBLANCA-XX', 'Vans', 'Hight Blanca'),
  ('Vans Hyline blanca', 'VANS-HIGHTBLANCA-XX', 'Vans', 'Hight Blanca'),
  ('Hyline negra', 'VANS-HIGHTNEGRA-XX', 'Vans', 'Hight Negra'),
  ('Vans Hyline negra', 'VANS-HIGHTNEGRA-XX', 'Vans', 'Hight Negra'),
  ('MQ BCO', 'MQCONCAMARA-BCO-XX', 'MQ', 'con Camara BCO'),
  ('MQ Blanca', 'MQCONCAMARA-BCO-XX', 'MQ', 'con Camara BCO'),
  ('MQ NE', 'MQCONCAMARA-NE-XX', 'MQ', 'con Camara NE'),
  ('MQ Negra', 'MQCONCAMARA-NE-XX', 'MQ', 'con Camara NE'),
  ('MQ Beige', 'MQCONCAMARA-BG-XX', 'MQ', 'con Camara BG'),
  ('MQ BG', 'MQCONCAMARA-BG-XX', 'MQ', 'con Camara BG'),
  ('MQ BB', 'MQSINCAMARA-MQBB-XX', 'MQ', 'Sin Camara BB'),
  ('MQ Black', 'MQSINCAMARA-MQBLACK-XX', 'MQ', 'Sin Camara Black'),
  ('MQ BN', 'MQSINCAMARA-MQBN-XX', 'MQ', 'Sin Camara BN'),
  ('MQ NB', 'MQSINCAMARA-MQNB-XX', 'MQ', 'Sin Camara NB'),
  ('MQ Roja Gamuza', 'MQ-SIN CAMARA RG-ROJO GAMUZA-XX', 'MQ', 'Sin Camara RG'),
  ('MQ Gamuza Roja', 'MQ-SIN CAMARA RG-ROJO GAMUZA-XX', 'MQ', 'Sin Camara RG'),
  ('MQ RG', 'MQ-SIN CAMARA RG-ROJO GAMUZA-XX', 'MQ', 'Sin Camara RG'),
  ('Baggy blanco', 'BAGGY-BLANCO-XX', 'Baggy', 'Baggy'),
  ('Baggy negro', 'BAGGY-NEGRO-XX', 'Baggy', 'Baggy'),
  ('Baggy gris claro', 'BAGGY-GRISCLARO-XX', 'Baggy', 'Baggy'),
  ('Baggy chocolate', 'BAGGY-CHOCOLATE-XX', 'Baggy', 'Baggy'),
  ('Joggin negro', 'JOGGIN-NEGRO-XX', 'Joggin', 'Joggin'),
  ('Joggin claro', 'JOGGIN-CLARO-XX', 'Joggin', 'Joggin'),
  ('Joggin gris claro', 'JOGGIN-GRISCLARO-XX', 'Joggin', 'Joggin'),
  ('Buzo blanco', 'BUZO-CANGURO-BLANCO-XX', 'Buzo', 'Canguro'),
  ('Buzo negro', 'BUZO-CANGURO-NEGRO-XX', 'Buzo', 'Canguro'),
  ('Hyline blanca', 'VANS-HIGHTBLANCA-XX', 'Vans', 'Hight Blanca'),
  ('Hyline negra', 'VANS-HIGHTNEGRA-XX', 'Vans', 'Hight Negra'),
  ('MQ NN', 'MQSINCAMARA-MQNN-XX', 'MQ', 'Sin Camara NN'),
  ('MQ rojo', 'MQSINCAMARA-MQROJO-XX', 'MQ', 'Sin Camara Rojo'),
  ('MQ roja', 'MQSINCAMARA-MQROJO-XX', 'MQ', 'Sin Camara Rojo'),
  ('270 gris', 'NIKE-270-GRIS TOPO-XX', 'Nike', '270'),
  ('270 gris topo', 'NIKE-270-GRIS TOPO-XX', 'Nike', '270'),
  ('270 topo', 'NIKE-270-GRIS TOPO-XX', 'Nike', '270'),
  ('270 azul', 'NIKE-270-AZUL-XX', 'Nike', '270'),
  ('Jordan blanca', 'JORDAN-BLANCA-41', 'Jordan', 'Jordan Blanca'),
  ('Puma rojo', 'PUMA-ROJO-XX', 'Puma', 'Puma Rojo'),
  ('Puma roja', 'PUMA-ROJO-XX', 'Puma', 'Puma Rojo'),
  ('Joggin gris uscuro', 'JOGGIN-GRISUSCURO-XX', 'Joggin', 'Joggin'),
  ('buzo gris', 'BUZO-CANGURO-GRISCLARO-XX', 'Buzo', 'Canguro'),
  ('Samba negra', 'ADIDAS-SAMBA-NEGRA-36', 'Adidas', 'Samba Negra'),
  ('Samba blanca', 'ADIDAS-SAMBA-BLANCA-39', 'Adidas', 'Samba Blanca');
